name: server
publish_to: none # not intended for publication to pub.dev

environment:
  sdk: ^3.5.1

dependencies:
  lsp_server: ^0.3.2
  shelf: ^1.4.0
  shelf_router: ^1.1.2
  shelf_static: ^1.1.0
  shelf_web_socket: ^2.0.0
  uuid: ^4.5.0

dev_dependencies:
  http: ^1.2.0
  lints: ^4.0.0
  test: ^1.25.0
  test_process: ^2.1.0